services:
  autotf.adminpanel:
    container_name: autotf_adminpanel
    image: 172.17.0.3:5001/repository/docker-autotf/autotf.adminpanel:latest
    restart: unless-stopped
#    Create .env file in same directory containing e.g. clientId=XXX
    environment:
      - ClientId=${ClientId}
      - Username=${Username}
      - Password=${Password}
      - AuthUrl=${AuthUrl}
      - CloudflareZone=${CloudflareZone}
      - CloudflareKey=${CloudflareKey}
    networks:
      authinstall_default: {}
    ports:
      - "8480:80"
      - "8481:81"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/sbin/plesk:/usr/sbin/plesk
      - /usr/local/plesk:/usr/local/plesk
      - /usr/local/psa:/usr/local/psa
      - /opt/plesk:/opt/plesk
      - /opt/psa:/opt/psa
      - /usr/bin/sw-engine
        
networks:
  authinstall_default:
    external: true
    
    useradd -r -u 999 -m psaadm